LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := OLARPlugin
LOCAL_SRC_FILES	:= OLARPlugin.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_CFLAGS := -I$(LOCAL_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := ARPluginCore
LOCAL_SRC_FILES	:= ARPluginCore.a 
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_CFLAGS := -I$(LOCAL_PATH)

include $(PREBUILT_STATIC_LIBRARY)
